### ISSUE TITLE
Cloud variables not getting creating

### ISSUE THREAD

**Issue by gregulator** [canopy-project/canopy-server#13]
Timo reports that this payload does not create new cloud variables on `haltian.canopy.link`, despite the response showing success:

    {"var_decls":{"out float64 batteryCurrLev":{"unit":"?"},"out float64 batteryCurrVol":{"unit":"?"},"out bool chargerConnect":{"unit":"?"}},"vars":{"batteryCurrLev":82,"batteryCurrVol":4.0510001183,"chargerConnect":0}}

I have confirmed the problem.

**Comment by gregulator** [comment]
Also noticed two related problems:
1) boolean cloud variables are not showing up and
2) the instructions for creating cloud variables are incorrect.

**Comment by tsdiebert** [comment]
1)         If the canopy_c_minimal library is being used, it would fail because the object after then name must be empty.  The API doc says the same thing.  I'm looking into the library to make sure that the boolean cloud variables work.

2)         I think that the API document is correct for creating cloud variables.  I'll double check that canopy_min.h is correct.

Tim

**Comment by tsdiebert** [comment]
It looks like the problem with bools is in the server.  This is the payload and device object output from toaster.  (I added a bool variable to it.)

~/.../canopy_c_minimal/example $ ./toaster 
Sending payload to dev02.canopy.link/api/device/self:
(null)

Returned from: dev02.canopy.link/api/device/self:
{
    "device_id": "e43eb410-48da-421a-b07d-1cd751412fd5",
    "friendly_name": "Toaster",
    "location_note": "mars",
    "notifs": [],
    "result": "ok",
    "secret_key": "wYI0G+HQN9fj76fpyxwiHKJDQags0dpM",
    "status": {
        "last_activity_time": 1428970222130345,
        "ws_connected": false
    },
    "var_decls": {
        "in bool reboot": {},
        "in float32 darkness": {},
        "inout float32 foobar": {},
        "out float32 temp_sensor": {}
    },
    "vars": {
        "darkness": {
            "t": 1428619964750000,
            "v": 3
        },
        "foobar": {
            "t": 1428619964749000,
            "v": 18.5
        },
        "temp_sensor": {
            "t": 1428969577863000,
            "v": 42
        }
    }
}

Sending payload to dev02.canopy.link/api/device/self:
    {
        "var_decls" : {  
            "out float32 temp_sensor" : {  
            }
            , "inout float32 foobar" : {  
            }
            , "in float32 darkness" : {  
            }
            , "in bool reboot" : {  
            }
        }
        , "vars" : {  
            "temp_sensor" : 4.200000e+01  
            , "reboot" : true  
        }
    }


Returned from: dev02.canopy.link/api/device/self:
{
    "device_id": "e43eb410-48da-421a-b07d-1cd751412fd5",
    "friendly_name": "Toaster",
    "location_note": "mars",
    "notifs": [],
    "result": "ok",
    "secret_key": "wYI0G+HQN9fj76fpyxwiHKJDQags0dpM",
    "status": {
        "last_activity_time": 1428970222370546,
        "ws_connected": false
    },
    "var_decls": {
        "in bool reboot": {},
        "in float32 darkness": {},
        "inout float32 foobar": {},
        "out float32 temp_sensor": {}
    },
    "vars": {
        "darkness": {
            "t": 1428619964750000,
            "v": 3
        },
        "foobar": {
            "t": 1428619964749000,
            "v": 18.5
        },
        "temp_sensor": {
            "t": 1428970222372000,
            "v": 42
        }
    }
}

darkness is 3.000000
last updated 1428619964750000
reboot is 0
last updated 0
~/.../canopy_c_minimal/example $
